enable bookworm installation by adapting python version
YunoHost-Apps/grist_ynh pull request #30
Opened 2024-05-11 06:22 UTC by Thovi98

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2024-05-11 06:22 UTC, Thovi98 commented
!testme

2024-05-11 08:02 UTC, fflorent approved these changes
Thanks!
Let's wait for the CI to complete and if it succeeds we'll merge

2024-05-12 17:44 UTC, alexAubin requested changes
This works but honestly this is just convoluted for nothing, let's just depend on `python3, python3-venv`, no need to specify the exact version...

2024-05-12 17:44 UTC, alexAubin commented on manifest.toml
> +    """
```suggestion
    package = "python3, python3-venv"
```

2024-05-12 17:46 UTC, Thovi98 commented on manifest.toml
> +    """
Agreed!

2024-05-12 18:29 UTC, fflorent commented
!testme

2024-05-12 21:39 UTC, fflorent approved these changes

2024-05-13 07:52 UTC, merged